
# Użyj oficjalnego obrazu OpenJDK 17 jako bazowego obrazu
FROM openjdk:17
# Ustal katalog roboczy w kontenerze
WORKDIR /app

# Skopiuj pliki aplikacji do kontenera
COPY ./build/libs/stocks-0.0.1-SNAPSHOT.jar /app/stocks-0.0.1-SNAPSHOT.jar
COPY ./src/main/resources/application.properties /app/config/application.properties
COPY ./Data /app/Data/

# Domyślny port, na którym działa aplikacja
EXPOSE 8081

# Komenda do uruchomienia aplikacji Spring Boot w kontenerze
CMD ["java", "-jar", "/app/stocks-0.0.1-SNAPSHOT.jar"]
